# Jekyll technical configuration!
#

remote_theme: "mmistakes/minimal-mistakes@4.21.0"

search             : true
search_full_content: true

# Site Settings
locale          : "de"
title           : "Knigge für Softwarearchitekten"
title_separator : "-"
name            : ""
description     : "Typische (gute und schlechte) Verhaltensmuster."
url             : "https://softwareknigge.de" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl         : ""  # the subpath of your site, e.g. "/blog"
repository      : "gernotstarke/softwareknigge.de-site" # GitHub username/repo-name
teaser          :  # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs     : false # true, false (default)
words_per_minute : 200
permalink       : none

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
# Social Sharing
twitter:
  username               : gernotstarke
  # For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             : "Dr. Gernot Starke"
  avatar           :  /images/Gernot-avatar-2016.jpg # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              :
  location         : "Köln"
  email            : gs@gernotstarke.de
  uri              : https://gernotstarke.de
  github           : gernotstarke
  google_plus      :
  stack_overflow   :
  twitter          : gernotstarke
  xing             : gernotstarke

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - Dockerfile
  - _docker-compose*
  - _manage-site.sh
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - originals


keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: coderay


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate:  # amount of posts to show
paginate_path: #/page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true

# Collections:
collections:
  negativ:
     output: true
     permalink: /:collection-posts/:title.html
  positiv:
       output: true
       permalink: /:collection-posts/:title.html
  neutral:
       output: true
       permalink: /:collection-posts/:title.html
